### ISSUE TITLE
suggestion: use GL_ARB_texture_swizzle for remove shader branching

### ISSUE THREAD

**Issue by mrgaturus** [liquid600pgm/rapid#18]
i use that extension for avoid putting bool uniforms and avoid using conditionals on my fragment shader, i mean, you can remove this:
```glsl
vec4 rTexel(sampler2D tex, vec2 uv) {
  if (rapid_textureEnabled) {
    if (rapid_renderText) {
      return vec4(vec3(1.0), texture(tex, uv).r);
    } else {
      return texture(tex, uv);
    }
  } else {
    return vec4(1.0);
  }
}
```
and simplify to:
```glsl
texture(tex, uv) * col;
```
because your 1byte per pixel (atlas) texture can be swizzled to (1,1,1,RED) and if you dont need UV coords you can default that uv attrib to a white pixel on atlas

**Comment by liquid600pgm** [comment]
I'd prefer to avoid using any extensions, as I can't be sure that all graphics cards/drivers support them (unlike the OpenGL standard, which I can rely on).

If I were to keep backwards compatibility, I'd need to keep two implementations of this function which only makes the problem worse.

**Comment by mrgaturus** [comment]
this extension is in OpenGL 3.3 Core Profile, the version of your glad.nim, but sadly, unsupported on WebGL and ES 2.0 (ES 3.0 supports it), so it can't be improved if you want target them. 
but at least there was the simplification possibility

**Comment by liquid600pgm** [comment]
Reopening this since aglet (rapid's new backend) will have this feature in the future.

**Comment by mrgaturus** [comment]
i have a working example [here](https://github.com/mrgaturus/npainter/blob/master/src/gui/atlas.nim#L357) using OpenGL 3.3 Core

**Comment by liquid600pgm** [comment]
Regarding conditionals in shaders, it's not that bad if you're testing against uniform variables, as the compiler can simply create multiple shaders with these branches precomputed. Even so, because driver implementations are known to be pretty inconsistent, implementing this should increase performance on some old, low-end GPUs. Or so I think.

**Comment by mrgaturus** [comment]
if your target is OpenGL 3.3+ and ES 3.x, you can use this feature without any problems. The oldest posible gpu is NVIDIA GeForce 210 (or 8400GS). An alternative for WebGL and ES 2.x (or below) is GL_ILUMINANCE format. The idea is simplify that shader code.

And for avoid this conditional:
```glsl
  if (rapid_textureEnabled) {
    // Check between alpha-only or color texture
    // (Job of texture swizzling)
  }
```
use an UV coordinate of a white pixel (1.0, 1.0, 1.0, 1.0) from your texture atlas, not only avoids that branching but also you can perform a batch optimization for glyph rendering and solid geometry rendering using fewer calls
